CREATE TABLE BKAUTC_#DATE_EXTRACT as
SELECT * FROM BKAUTC
##
CREATE TABLE BKCAU_#DATE_EXTRACT AS
SELECT * FROM BKCAU
##
CREATE TABLE BKCLIPRT_#DATE_EXTRACT AS
SELECT * FROM BKCLIPRT
##
CREATE TABLE BKCOM_#DATE_EXTRACT AS
SELECT * FROM BKCOM

##
CREATE TABLE BKDOSPRT_#DATE_EXTRACT AS
SELECT * FROM BKDOSPRT
##
CREATE TABLE BKENG_#DATE_EXTRACT AS
SELECT * FROM BKENG
##
CREATE TABLE BKGAR_#DATE_EXTRACT AS
SELECT * FROM BKGAR
##
CREATE TABLE BKGRP_#DATE_EXTRACT AS
SELECT * FROM BKGRP
##
CREATE TABLE BKNOM_#DATE_EXTRACT AS
SELECT * FROM BKNOM
##
CREATE TABLE BKECHPRT_#DATE_EXTRACT AS
SELECT * FROM BKECHPRT
##
CREATE TABLE BKEFR_#DATE_EXTRACT AS
SELECT * FROM BKEFR
##
CREATE TABLE BKHISEFR_#DATE_EXTRACT AS
SELECT * FROM BKHISEFR
##

CREATE TABLE BKEFR_#DATE_EXTRACT AS
SELECT *
FROM BKEFR
