Select
    FILIALE,
    to_char(DATE_EXTRACT, 'DD/MM/YYYY') "DATE_REFERENCE",
    CODE_CLIENT "CODE_CLIENT",
    NUM_COMPTE "NUM_COMPTE_COURANT",
    NOM_CLIENT "NOM_ET_PRENOM",
    CUMUL_CREIT_6MOIS "CUMUL_MVT_CREDIT",
    CUMUL_AGIOS_6MOIS "AGIOS",
    deb6M "SOLDE",
    DUREE
from
    ORA_DATARISK5
where
    deb6M != 0;